[[constraint]]
  name = "github.com/hyperledger/fabric"
  version = "1.0.3"

[[constraint]]
  name = "github.com/stratumn/sdk"
  branch = "master"

[[override]]
  branch = "master"
  name = "github.com/op/go-logging"

[[override]]
  name = "github.com/fsouza/go-dockerclient"
  revision = "d433254bb83b41d7072ce470e312ea3cee257882"

[[override]]
  name = "github.com/spf13/viper"
  revision = "1967d93db724f4a5c0e101307e96d82ff520a067"

[[override]]
  name = "golang.org/x/crypto"
  revision = "81bf7719a6b7ce9b665598222362b50122dfc13b"

[[override]]
  name = "golang.org/x/sys"
  revision = "c200b10b5d5e122be351b67af224adc6128af5bf"